# Top-level docker compose file.
#
# Each service has its own docker-compose.yml file, services are stored in
# folders under the `services` folder. The `COMPOSE_FILE` environment
# variable is used to tell Docker to load all of the compose files that
# will be in use. The `COMPOSE_FILE` variable is set in the `env.sh` script.
#
# This separation allows services to be enabled/disabled as required per
# environment. It also provides a logical way to group resources together for
# each service.

# Networks
# --------
#
# Networks defined here are made available to other projects containers running
# on this host. This avoids services from other projects which use web-router
# failing to start, even if the services which these networks relate to are not
# enabled. For example, if traefik is not enabled, by defining the `web-router`
# network here those services will still start.
networks:
  # Traefik network.
  # Any services on the host which want to be available through Traefik must
  # join the `web-router` network.
  web-router:
    driver: bridge
    name: web-router
