name: Tests

on: push

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull images used during tests
        run: docker pull nginx
      - name: Run tests
        run: cd tests && ./run.sh
